apiVersion: v1
kind: Service
metadata:
  name: first-service
spec:
  selector:
    app: web-server
  type: NodePort
  ports:
    - protocol: TCP
      nodePort: 30390
      port: 3000
      targetPort: 3000