apiVersion: v1
kind: Pod
metadata:
  name: first-pod
  labels:
    role: first-pod
    app: web-server
    annotation: first-pod
spec:
  containers:
    - name: first-pod
      image: cutechuanchuan/nodejs-example:1.0.0
      imagePullPolicy: Always
      ports:
        - containerPort: 3000
  