apiVersion: v1
kind: Pod
metadata:
  name: pod-secret-way2
  labels:
    app: web-server-secret-way2
spec:
  containers:
    - name: pod-secret-way2
      image: cutechuanchuan/nodejs-example:2.0.0
      imagePullPolicy: Always
      ports:
        - containerPort: 80
      volumeMounts:
        - mountPath: /etc/secret
          name: secret-volume
          readOnly: true
  volumes:
    - name: secret-volume
      secret:
        secretName: secret-from-yaml-encode
  restartPolicy: Always
  