apiVersion: v1
kind: Pod
metadata:
  name: pod-secret-way1
  labels:
    app: web-server-secret-way1
spec:
  containers:
    - name: pod-secret-way1
      image: cutechuanchuan/nodejs-example:2.0.0
      imagePullPolicy: Always
      ports:
        - containerPort: 3000
      env:
        - name: SECRET_USERNAME
          valueFrom:
            secretKeyRef:
              name: secret-from-yaml-encode
              key: username
        - name: SECRET_PASSWORD
          valueFrom:
            secretKeyRef:
              name: secret-from-yaml-encode
              key: password

  restartPolicy: Always
  